In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [79]:
data2017 = pd.read_excel('Métricas.xlsx',sheet_name=0)
data2018 = pd.read_excel('Métricas.xlsx',sheet_name=1)
data2019 = pd.read_excel('Métricas.xlsx',sheet_name=2)

In [80]:
label_2017=data2017.values[:,3]
label_2018=data2018.values[:,3]
label_2019=data2019.values[:,3]
n2017=data2017.values[:,0]
n2018=data2018.values[:,0]
n2019=data2019.values[:,0]
rent_2017=data2017.values[:,4]
rent_2018=data2018.values[:,4]
rent_2019=data2019.values[:,4]
pl_2017=data2017.values[:,1]
pl_2018=data2018.values[:,1]
pl_2019=data2019.values[:,1]
roe_2017=data2017.values[:,2]
roe_2018=data2018.values[:,2]
roe_2019=data2019.values[:,2]

In [21]:
######## Ano de 2017
CLUSTER_2017=[]
for j in range(10):
    CLUSTER_2017.append([])
for i in range(len(label_2017)):
    for j in range(10):
        if label_2017[i] == j:
            CLUSTER_2017[j].append(n2017[i])
######## Ano de 2018
CLUSTER_2018=[]
for j in range(10):
    CLUSTER_2018.append([])
for i in range(len(label_2018)):
    for j in range(10):
        if label_2018[i] == j:
            CLUSTER_2018[j].append(n2018[i])
######## Ano de 2019
CLUSTER_2019=[]
for j in range(10):
    CLUSTER_2019.append([])
for i in range(len(label_2019)):
    for j in range(10):
        if label_2019[i] == j:
            CLUSTER_2019[j].append(n2019[i])

RENTABILIDADE MÉDIA DAS AÇÕES DO IBOVESPA E RENTABILIDADE DO IBOVESPA

In [25]:
bova = [1.1704394582134192, 1.2996586562075974, 0.9986869614085797]
mercado=[np.sum(rent_2017)/len(rent_2017),np.sum(rent_2018)/len(rent_2018),np.sum(rent_2019)/len(rent_2019)]

RENTABILIDADE DAS TOP 10 MENORES PREÇO/LUCRO DA IBOVESPA

In [39]:
top10_pl_2017 = []
aux=pl_2017.copy()
for i in range(len(aux)):
    if aux[i]<0:
        aux[i]=10000
for i in range(10):
    top10_pl_2017.append(rent_2017[np.argmin(aux)])
    aux[np.argmin(aux)]=10000
nomes=[]
pos=[]
for i in range(10):
    J = np.where(rent_2017==top10_pl_2017[i])[0][0]
    nomes.append(n2017[J])
    pos.append(J)
rent_top10_pl_2017 = np.sum(top10_pl_2017)/10
np.array(nomes),label_2017[pos],rent_top10_pl_2017

(array(['BRAP4', 'SMLS3', 'BBAS3', 'BRKM5', 'MRVE3', 'ITSA4', 'CMIG4',
        'SBSP3', 'EGIE3', 'ITUB4'], dtype='<U5'),
 array([2, 5, 1, 8, 4, 1, 6, 0, 3, 1], dtype=object),
 1.2689484048456023)

In [40]:
top10_pl_2018 = []
aux=pl_2018.copy()
for i in range(len(aux)):
    if aux[i]<0:
        aux[i]=10000
for i in range(10):
    top10_pl_2018.append(rent_2018[np.argmin(aux)])
    aux[np.argmin(aux)]=10000
nomes=[]
pos=[]
for i in range(10):
    J = np.where(rent_2018==top10_pl_2018[i])[0][0]
    nomes.append(n2018[J])
    pos.append(J)
rent_top10_pl_2018 = np.sum(top10_pl_2018)/10
np.array(nomes),label_2018[pos],rent_top10_pl_2018

(array(['ELET3', 'CSNA3', 'MRFG3', 'ELET6', 'SMLS3', 'ENBR3', 'VIVT3',
        'MRVE3', 'CIEL3', 'TAEE11'], dtype='<U6'),
 array([8, 3, 6, 8, 2, 9, 0, 5, 9, 9], dtype=object),
 1.4518919071622052)

In [41]:
top10_pl_2019 = []
aux=pl_2019.copy()
for i in range(len(aux)):
    if aux[i]<0:
        aux[i]=10000
for i in range(10):
    top10_pl_2019.append(rent_2019[np.argmin(aux)])
    aux[np.argmin(aux)]=10000
nomes=[]
pos=[]
for i in range(10):
    J = np.where(rent_2019==top10_pl_2019[i])[0][0]
    nomes.append(n2019[J])
    pos.append(J)
rent_top10_pl_2019 = np.sum(top10_pl_2019)/10
np.array(nomes),label_2019[pos],rent_top10_pl_2019

(array(['ELET3', 'ELET6', 'SMLS3', 'CMIG4', 'BBAS3', 'EQTL3', 'ENBR3',
        'BBSE3', 'TIMS3', 'TAEE11'], dtype='<U6'),
 array([2, 2, 4, 2, 6, 3, 2, 8, 9, 2], dtype=object),
 0.9676229150196269)

RENTABILIDADE DAS TOP 10 MAIORES ROES DA IBOVESPA

In [36]:
top10_roe_2017 = []
aux=roe_2017.copy()
for i in range(10):
    top10_roe_2017.append(rent_2017[np.argmax(aux)])
    aux[np.argmax(aux)]=0
nomes=[]
pos=[]
for i in range(10):
    J = np.where(rent_2017==top10_roe_2017[i])[0][0]
    nomes.append(n2017[J])
    pos.append(J)
rent_top10_roe_2017 = np.sum(top10_roe_2017)/10
np.array(nomes),label_2017[pos],rent_top10_roe_2017

(array(['BRKM5', 'ECOR3', 'SMLS3', 'BBSE3', 'NTCO3', 'CIEL3', 'EGIE3',
        'CVCB3', 'BRAP4', 'IRBR3'], dtype='<U5'),
 array([8, 3, 5, 3, 4, 3, 3, 0, 2, 7], dtype=object),
 1.13323258814654)

In [37]:
top10_roe_2018 = []
aux=roe_2018.copy()
for i in range(10):
    top10_roe_2018.append(rent_2018[np.argmax(aux)])
    aux[np.argmax(aux)]=0
nomes=[]
pos=[]
for i in range(10):
    J = np.where(rent_2018==top10_roe_2018[i])[0][0]
    nomes.append(n2018[J])
    pos.append(J)
rent_top10_roe_2018 = np.sum(top10_roe_2018)/10
np.array(nomes),label_2018[pos],rent_top10_roe_2018

(array(['MRFG3', 'SMLS3', 'ECOR3', 'CSNA3', 'BBSE3', 'BRKM5', 'EGIE3',
        'BRDT3', 'IRBR3', 'CIEL3'], dtype='<U5'),
 array([6, 2, 6, 3, 5, 4, 4, 7, 4, 9], dtype=object),
 1.3693402683644622)

In [87]:
top10_roe_2019 = []
aux=roe_2019.copy()
for i in range(10):
    top10_roe_2019.append(rent_2019[np.argmax(aux)])
    aux[np.argmax(aux)]=0
nomes=[]
pos=[]
for i in range(10):
    J = np.where(rent_2019==top10_roe_2019[i])[0][0]
    nomes.append(n2019[J])
    pos.append(J)
rent_top10_roe_2019 = np.sum(top10_roe_2019)/10
np.array(nomes),label_2019[pos],rent_top10_roe_2019

(array(['BBSE3', 'AZUL4', 'SMLS3', 'MRFG3', 'EGIE3', 'IRBR3', 'EQTL3',
        'QUAL3', 'BRDT3', 'LREN3'], dtype='<U5'),
 array([8, 4, 4, 0, 9, 0, 3, 0, 2, 1], dtype=object),
 0.820480466420203)

RENTABILIDADE DA NOSSA ESTRATÉGIA, PEGANDO A AÇÃO DE CADA CLUSTER COM O MENOR P/L

In [55]:
nomes=[]
pos=[]
carteira_pl_2017=np.zeros(10)
aux=100*np.ones(10)
for i in range(10):
    for j in range(len(pl_2017)):
        if label_2017[j] == i:
            if pl_2017[j] > 0 and pl_2017[j] < aux[i]:
                carteira_pl_2017[i]= rent_2017[j]
                aux[i] = pl_2017[j]
for i in range(10):
    J = np.where(rent_2017==carteira_pl_2017[i])[0][0]
    nomes.append(n2017[J])
    pos.append(J)
rent_carteira_pl_2017 = np.sum(carteira_pl_2017)/10
np.array(nomes),label_2017[pos],rent_carteira_pl_2017

(array(['SBSP3', 'BBAS3', 'BRAP4', 'EGIE3', 'MRVE3', 'SMLS3', 'CMIG4',
        'IRBR3', 'BRKM5', 'VIVT3'], dtype='<U5'),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object),
 1.358262163370678)

In [56]:
nomes=[]
carteira_pl_2018=np.zeros(10)
aux=100*np.ones(10)
pos=[]
for i in range(10):
    for j in range(len(pl_2018)):
        if label_2018[j] == i:
            if pl_2018[j] > 0 and pl_2018[j] < aux[i]:
                carteira_pl_2018[i]= rent_2018[j]
                aux[i] = pl_2018[j]
for i in range(10):
    J = np.where(rent_2018==carteira_pl_2018[i])[0][0]
    nomes.append(n2018[J])
    pos.append(J)
rent_carteira_pl_2018 = np.sum(carteira_pl_2018)/10
np.array(nomes),label_2018[pos],rent_carteira_pl_2018

(array(['VIVT3', 'BRML3', 'SMLS3', 'CSNA3', 'EGIE3', 'MRVE3', 'MRFG3',
        'BRDT3', 'ELET3', 'ENBR3'], dtype='<U5'),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object),
 1.5353840577187428)

In [57]:
nomes=[]
pos=[]
carteira_pl_2019=np.zeros(10)
aux=100*np.ones(10)
for i in range(10):
    for j in range(len(pl_2019)):
        if label_2019[j] == i:
            if pl_2019[j] > 0 and pl_2019[j] < aux[i]:
                carteira_pl_2019[i]= rent_2019[j]
                aux[i] = pl_2019[j]
for i in range(10):
    J = np.where(rent_2019==carteira_pl_2019[i])[0][0]
    nomes.append(n2019[J])
    pos.append(J)
rent_carteira_pl_2019 = np.sum(carteira_pl_2019)/10
np.array(nomes),label_2019[pos],rent_carteira_pl_2019

(array(['JBSS3', 'BRML3', 'ELET3', 'EQTL3', 'SMLS3', 'PETR4', 'BBAS3',
        'CSNA3', 'BBSE3', 'TIMS3'], dtype='<U5'),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object),
 1.0100619345272934)

RENTABILIDADE DA NOSSA ESTRATÉGIA, PEGANDO A AÇÃO DE CADA CLUSTER COM O MAIOR ROE

In [58]:
nomes=[]
pos=[]
carteira_roe_2017=np.zeros(10)
aux=np.zeros(10)
for i in range(10):
    for j in range(len(roe_2017)):
        if label_2017[j] == i:
            if roe_2017[j] > 0 and roe_2017[j] > aux[i]:
                carteira_roe_2017[i]= rent_2017[j]
                aux[i] = roe_2017[j]
for i in range(10):
    J = np.where(rent_2017==carteira_roe_2017[i])[0][0]
    nomes.append(n2017[J])
    pos.append(J)
rent_carteira_roe_2017 = np.sum(carteira_roe_2017)/10
np.array(nomes),label_2017[pos],rent_carteira_roe_2017

(array(['CVCB3', 'ITUB4', 'BRAP4', 'ECOR3', 'NTCO3', 'SMLS3', 'CMIG4',
        'IRBR3', 'BRKM5', 'FLRY3'], dtype='<U5'),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object),
 1.2698575544797777)

In [91]:
nomes=[]
pos=[]
carteira_roe_2018=np.zeros(10)
aux=np.zeros(10)
for i in range(10):
    for j in range(len(roe_2018)):
        if label_2018[j] == i:
            if roe_2018[j] > 0 and roe_2018[j] > aux[i]:
                carteira_roe_2018[i]= rent_2018[j]
                aux[i] = roe_2018[j]
for i in range(10):
    J = np.where(rent_2018==carteira_roe_2018[i])[0][0]
    nomes.append(n2018[J])
    pos.append(J)
rent_carteira_roe_2018 = np.sum(carteira_roe_2018)/10
np.array(nomes),label_2018[pos],rent_carteira_roe_2018

(array(['ABEV3', 'LREN3', 'SMLS3', 'CSNA3', 'BRKM5', 'BBSE3', 'MRFG3',
        'BRDT3', 'ELET3', 'CIEL3'], dtype='<U5'),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object),
 1.3283265968481364)

In [81]:
nomes=[]
pos=[]
carteira_roe_2019=np.zeros(10)
aux=np.zeros(10)
for i in range(10):
    for j in range(len(roe_2019)):
        if label_2019[j] == i:
            if roe_2019[j] > 0 and roe_2019[j] > aux[i]:
                carteira_roe_2019[i]= rent_2019[j]
                aux[i] = roe_2019[j]
for i in range(10):
    J = np.where(rent_2019==carteira_roe_2019[i])[0][0]
    nomes.append(n2019[J])
    pos.append(J)
rent_carteira_roe_2019 = np.sum(carteira_roe_2019)/10
np.array(nomes),label_2019[pos],rent_carteira_roe_2019

(array(['MRFG3', 'LREN3', 'BRDT3', 'EQTL3', 'AZUL4', 'PETR3', 'ITUB4',
        'CSNA3', 'BBSE3', 'EGIE3'], dtype='<U5'),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object),
 1.0406869338544014)

COMPARAÇÕES, CAPITAL INICIAL DE 10.000 EM CADA UM DOS CASOS

In [88]:
C = 10_000
a1 = C*bova[0]*bova[1]*bova[2]
a2 = C*mercado[0]*mercado[1]*mercado[2]
a3 = C*rent_top10_pl_2017 *rent_top10_pl_2018*rent_top10_pl_2019
a4 = C*rent_top10_roe_2017 *rent_top10_roe_2018*rent_top10_roe_2019
a5 = C*rent_carteira_pl_2017*rent_carteira_pl_2018*rent_carteira_pl_2019
a6 = C*rent_carteira_roe_2017*rent_carteira_roe_2018*rent_carteira_roe_2019

In [89]:
comparacao={}
comparacao['IBOVESPA'] = a1
comparacao['MÉDIA DO MERCADO'] = a2
comparacao['TOP 10 PREÇO/LUCRO'] = a3
comparacao['TOP 10 ROE'] = a4
comparacao['CLUSTERING + PREÇO/LUCRO'] = a5
comparacao['CLUSTERING + ROE'] = a6

In [90]:
comparacao

{'IBOVESPA': 15191.744161913024,
 'MÉDIA DO MERCADO': 17822.99106712762,
 'TOP 10 PREÇO/LUCRO': 17827.25157886982,
 'TOP 10 ROE': 12732.060120948638,
 'CLUSTERING + PREÇO/LUCRO': 21064.377741724602,
 'CLUSTERING + ROE': 17554.156964858874}